import type { Metadata } from "next";

import "./globals.css";

// This layout is used to wrap all pages in the application.

export const metadata: Metadata = {
  title: "CGP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      
      >
        {children}
      </body>
    </html>
  );
}
